//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtLinkAdministracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospect
    {
        public int id_prospecto { get; set; }
        public string RFC { get; set; }
        public string RazonSocial { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Vendedor { get; set; }
        public string Fechacontacto { get; set; }
        public string Tipocliente { get; set; }
    }
}
