//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.1.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/arrendamientoenfideicomiso")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/arrendamientoenfideicomiso", IsNullable=false)]
public partial class Arrendamientoenfideicomiso {
    
    private string versionField;
    
    private decimal pagProvEfecPorFiducField;
    
    private decimal rendimFideicomField;
    
    private decimal deduccCorrespField;
    
    private decimal montTotRetField;
    
    private bool montTotRetFieldSpecified;
    
    private decimal montResFiscDistFibrasField;
    
    private bool montResFiscDistFibrasFieldSpecified;
    
    private decimal montOtrosConceptDistrField;
    
    private bool montOtrosConceptDistrFieldSpecified;
    
    private string descrMontOtrosConceptDistrField;
    
    public Arrendamientoenfideicomiso() {
        this.versionField = "1.0";
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PagProvEfecPorFiduc {
        get {
            return this.pagProvEfecPorFiducField;
        }
        set {
            this.pagProvEfecPorFiducField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal RendimFideicom {
        get {
            return this.rendimFideicomField;
        }
        set {
            this.rendimFideicomField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal DeduccCorresp {
        get {
            return this.deduccCorrespField;
        }
        set {
            this.deduccCorrespField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal MontTotRet {
        get {
            return this.montTotRetField;
        }
        set {
            this.montTotRetField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MontTotRetSpecified {
        get {
            return this.montTotRetFieldSpecified;
        }
        set {
            this.montTotRetFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal MontResFiscDistFibras {
        get {
            return this.montResFiscDistFibrasField;
        }
        set {
            this.montResFiscDistFibrasField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MontResFiscDistFibrasSpecified {
        get {
            return this.montResFiscDistFibrasFieldSpecified;
        }
        set {
            this.montResFiscDistFibrasFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal MontOtrosConceptDistr {
        get {
            return this.montOtrosConceptDistrField;
        }
        set {
            this.montOtrosConceptDistrField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MontOtrosConceptDistrSpecified {
        get {
            return this.montOtrosConceptDistrFieldSpecified;
        }
        set {
            this.montOtrosConceptDistrFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DescrMontOtrosConceptDistr {
        get {
            return this.descrMontOtrosConceptDistrField;
        }
        set {
            this.descrMontOtrosConceptDistrField = value;
        }
    }
}
