//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Xml.Schema;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.1.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/fideicomisonoempresarial")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/fideicomisonoempresarial", IsNullable=false)]
public partial class Fideicomisonoempresarial {

    [XmlAttribute("schemaLocation", Namespace = XmlSchema.InstanceNamespace)]
    public string xsiSchemaLocation =
        "http://www.sat.gob.mx/esquemas/retencionpago/1/fideicomisonoempresarial http://www.sat.gob.mx/esquemas/retencionpago/1/fideicomisonoempresarial/fideicomisonoempresarial.xsd";


    private FideicomisonoempresarialIngresosOEntradas ingresosOEntradasField;
    
    private FideicomisonoempresarialDeduccOSalidas deduccOSalidasField;
    
    private FideicomisonoempresarialRetEfectFideicomiso retEfectFideicomisoField;
    
    private string versionField;
    
    public Fideicomisonoempresarial() {
        this.versionField = "1.0";
    }
    
    /// <comentarios/>
    public FideicomisonoempresarialIngresosOEntradas IngresosOEntradas {
        get {
            return this.ingresosOEntradasField;
        }
        set {
            this.ingresosOEntradasField = value;
        }
    }
    
    /// <comentarios/>
    public FideicomisonoempresarialDeduccOSalidas DeduccOSalidas {
        get {
            return this.deduccOSalidasField;
        }
        set {
            this.deduccOSalidasField = value;
        }
    }
    
    /// <comentarios/>
    public FideicomisonoempresarialRetEfectFideicomiso RetEfectFideicomiso {
        get {
            return this.retEfectFideicomisoField;
        }
        set {
            this.retEfectFideicomisoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/fideicomisonoempresarial")]
public partial class FideicomisonoempresarialIngresosOEntradas {
    
    private FideicomisonoempresarialIngresosOEntradasIntegracIngresos integracIngresosField;
    
    private decimal montTotEntradasPeriodoField;
    
    private decimal partPropAcumDelFideicomField;
    
    private decimal propDelMontTotField;
    
    /// <comentarios/>
    public FideicomisonoempresarialIngresosOEntradasIntegracIngresos IntegracIngresos {
        get {
            return this.integracIngresosField;
        }
        set {
            this.integracIngresosField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal MontTotEntradasPeriodo {
        get {
            return this.montTotEntradasPeriodoField;
        }
        set {
            this.montTotEntradasPeriodoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PartPropAcumDelFideicom {
        get {
            return this.partPropAcumDelFideicomField;
        }
        set {
            this.partPropAcumDelFideicomField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PropDelMontTot {
        get {
            return this.propDelMontTotField;
        }
        set {
            this.propDelMontTotField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/fideicomisonoempresarial")]
public partial class FideicomisonoempresarialIngresosOEntradasIntegracIngresos {
    
    private string conceptoField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Concepto {
        get {
            return this.conceptoField;
        }
        set {
            this.conceptoField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/fideicomisonoempresarial")]
public partial class FideicomisonoempresarialDeduccOSalidas {
    
    private FideicomisonoempresarialDeduccOSalidasIntegracEgresos integracEgresosField;
    
    private decimal montTotEgresPeriodoField;
    
    private decimal partPropDelFideicomField;
    
    private string propDelMontTotField;
    
    /// <comentarios/>
    public FideicomisonoempresarialDeduccOSalidasIntegracEgresos IntegracEgresos {
        get {
            return this.integracEgresosField;
        }
        set {
            this.integracEgresosField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal MontTotEgresPeriodo {
        get {
            return this.montTotEgresPeriodoField;
        }
        set {
            this.montTotEgresPeriodoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PartPropDelFideicom {
        get {
            return this.partPropDelFideicomField;
        }
        set {
            this.partPropDelFideicomField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PropDelMontTot {
        get {
            return this.propDelMontTotField;
        }
        set {
            this.propDelMontTotField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/fideicomisonoempresarial")]
public partial class FideicomisonoempresarialDeduccOSalidasIntegracEgresos {
    
    private string conceptoSField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ConceptoS {
        get {
            return this.conceptoSField;
        }
        set {
            this.conceptoSField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/fideicomisonoempresarial")]
public partial class FideicomisonoempresarialRetEfectFideicomiso {
    
    private decimal montRetRelPagFideicField;
    
    private string descRetRelPagFideicField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal MontRetRelPagFideic {
        get {
            return this.montRetRelPagFideicField;
        }
        set {
            this.montRetRelPagFideicField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DescRetRelPagFideic {
        get {
            return this.descRetRelPagFideicField;
        }
        set {
            this.descRetRelPagFideicField = value;
        }
    }
}
