//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Xml.Schema;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.1.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/intereses")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/intereses", IsNullable=false)]
public partial class Intereses {

   // [XmlAttribute("schemaLocation", Namespace = XmlSchema.InstanceNamespace)]
   // public string xsiSchemaLocation = "http://www.sat.gob.mx/esquemas/retencionpago/1/intereses http://www.sat.gob.mx/esquemas/retencionpago/1/intereses/intereses.xsd";
      

    private string versionField;
    
    private InteresesSistFinanciero sistFinancieroField;
    
    private InteresesRetiroAORESRetInt retiroAORESRetIntField;
    
    private InteresesOperFinancDerivad operFinancDerivadField;
    
    private decimal montIntNominalField;
    
    private decimal montIntRealField;
    
    private decimal perdidaField;
    
    public Intereses() {
        this.versionField = "1.0";
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public InteresesSistFinanciero SistFinanciero {
        get {
            return this.sistFinancieroField;
        }
        set {
            this.sistFinancieroField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public InteresesRetiroAORESRetInt RetiroAORESRetInt {
        get {
            return this.retiroAORESRetIntField;
        }
        set {
            this.retiroAORESRetIntField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public InteresesOperFinancDerivad OperFinancDerivad {
        get {
            return this.operFinancDerivadField;
        }
        set {
            this.operFinancDerivadField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal MontIntNominal {
        get {
            return this.montIntNominalField;
        }
        set {
            this.montIntNominalField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal MontIntReal {
        get {
            return this.montIntRealField;
        }
        set {
            this.montIntRealField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Perdida {
        get {
            return this.perdidaField;
        }
        set {
            this.perdidaField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/intereses")]
public enum InteresesSistFinanciero {
    
    /// <comentarios/>
    SI,
    
    /// <comentarios/>
    NO,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/intereses")]
public enum InteresesRetiroAORESRetInt {
    
    /// <comentarios/>
    SI,
    
    /// <comentarios/>
    NO,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/intereses")]
public enum InteresesOperFinancDerivad {
    
    /// <comentarios/>
    SI,
    
    /// <comentarios/>
    NO,
}
