//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Xml.Schema;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.1.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/pagosaextranjeros")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/pagosaextranjeros", IsNullable=false)]
public partial class Pagosaextranjeros {

    [XmlAttribute("schemaLocation", Namespace = XmlSchema.InstanceNamespace)]
    public string xsiSchemaLocation =
        "http://www.sat.gob.mx/esquemas/retencionpago/1/pagosaextranjeros http://www.sat.gob.mx/esquemas/retencionpago/1/pagosaextranjeros/pagosaextranjeros.xsd";


    private PagosaextranjerosNoBeneficiario noBeneficiarioField;
    
    private PagosaextranjerosBeneficiario beneficiarioField;
    
    private string versionField;
    
    private PagosaextranjerosEsBenefEfectDelCobro esBenefEfectDelCobroField;
    
    public Pagosaextranjeros() {
        this.versionField = "1.0";
    }
    
    /// <comentarios/>
    public PagosaextranjerosNoBeneficiario NoBeneficiario {
        get {
            return this.noBeneficiarioField;
        }
        set {
            this.noBeneficiarioField = value;
        }
    }
    
    /// <comentarios/>
    public PagosaextranjerosBeneficiario Beneficiario {
        get {
            return this.beneficiarioField;
        }
        set {
            this.beneficiarioField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PagosaextranjerosEsBenefEfectDelCobro EsBenefEfectDelCobro {
        get {
            return this.esBenefEfectDelCobroField;
        }
        set {
            this.esBenefEfectDelCobroField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/pagosaextranjeros")]
public partial class PagosaextranjerosNoBeneficiario {
    
    private string paisDeResidParaEfecFiscField;
    
    private string conceptoPagoField;
    
    private string descripcionConceptoField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PaisDeResidParaEfecFisc {
        get {
            return this.paisDeResidParaEfecFiscField;
        }
        set {
            this.paisDeResidParaEfecFiscField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ConceptoPago {
        get {
            return this.conceptoPagoField;
        }
        set {
            this.conceptoPagoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DescripcionConcepto {
        get {
            return this.descripcionConceptoField;
        }
        set {
            this.descripcionConceptoField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/pagosaextranjeros")]
public partial class PagosaextranjerosBeneficiario {
    
    private string rFCField;
    
    private string cURPField;
    
    private string nomDenRazSocBField;
    
    private string conceptoPagoField;
    
    private string descripcionConceptoField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RFC {
        get {
            return this.rFCField;
        }
        set {
            this.rFCField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CURP {
        get {
            return this.cURPField;
        }
        set {
            this.cURPField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NomDenRazSocB {
        get {
            return this.nomDenRazSocBField;
        }
        set {
            this.nomDenRazSocBField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ConceptoPago {
        get {
            return this.conceptoPagoField;
        }
        set {
            this.conceptoPagoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DescripcionConcepto {
        get {
            return this.descripcionConceptoField;
        }
        set {
            this.descripcionConceptoField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/retencionpago/1/pagosaextranjeros")]
public enum PagosaextranjerosEsBenefEfectDelCobro {
    
    /// <comentarios/>
    SI,
    
    /// <comentarios/>
    NO,
}
