//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioLocal.Business.InternalCertificador {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InternalCertificador.ICertificadorApps")]
    internal interface ICertificadorApps {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificadorApps/TimbraCfdi", ReplyAction="http://tempuri.org/ICertificadorApps/TimbraCfdiResponse")]
        string TimbraCfdi(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificadorApps/TimbraRetencion", ReplyAction="http://tempuri.org/ICertificadorApps/TimbraRetencionResponse")]
        string TimbraRetencion(string userName, string password, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificadorApps/Ping", ReplyAction="http://tempuri.org/ICertificadorApps/PingResponse")]
        string Ping();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ICertificadorAppsChannel : ServicioLocal.Business.InternalCertificador.ICertificadorApps, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class CertificadorAppsClient : System.ServiceModel.ClientBase<ServicioLocal.Business.InternalCertificador.ICertificadorApps>, ServicioLocal.Business.InternalCertificador.ICertificadorApps {
        
        public CertificadorAppsClient() {
        }
        
        public CertificadorAppsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CertificadorAppsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificadorAppsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificadorAppsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TimbraCfdi(string userName, string password, string comprobante) {
            return base.Channel.TimbraCfdi(userName, password, comprobante);
        }
        
        public string TimbraRetencion(string userName, string password, string comprobante) {
            return base.Channel.TimbraRetencion(userName, password, comprobante);
        }
        
        public string Ping() {
            return base.Channel.Ping();
        }
    }
}
