//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Xml.Schema;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.1.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.amazon.com.mx/AmazonAddenda")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.amazon.com.mx/AmazonAddenda", IsNullable=false)]
public partial class ElementosAmazon {
    
    [XmlAttribute("schemaLocation", AttributeName = "schemaLocation", Namespace = XmlSchema.InstanceNamespace)]
    public string xsiSchemaLocation =
        "http://www.amazon.com.mx/AmazonAddenda http://repository.edicomnet.com/schemas/mx/cfd/addenda/AmazonAddenda.xsd";
    
    private string textoLibreField;
    
    private ElementosAmazonLosAtributos[] losAtributosField;
    
    /// <comentarios/>
    public string TextoLibre {
        get {
            return this.textoLibreField;
        }
        set {
            this.textoLibreField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("LosAtributos")]
    public ElementosAmazonLosAtributos[] LosAtributos {
        get {
            return this.losAtributosField;
        }
        set {
            this.losAtributosField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.amazon.com.mx/AmazonAddenda")]
public partial class ElementosAmazonLosAtributos {
    
    private string identificacionUnicaField;
    
    private string nombreDelAtributoField;
    
    private string valorDelAtributoField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string identificacionUnica {
        get {
            return this.identificacionUnicaField;
        }
        set {
            this.identificacionUnicaField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nombreDelAtributo {
        get {
            return this.nombreDelAtributoField;
        }
        set {
            this.nombreDelAtributoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string valorDelAtributo {
        get {
            return this.valorDelAtributoField;
        }
        set {
            this.valorDelAtributoField = value;
        }
    }
}
